name = input("Ayrton")
print("Hello" + name)
age = input("14 ")
addr = input("Iligan City ")
print(name + " lives in Iligan City " + addr)
year = 2026 - int(14) 
print("Born in: " + str(2012))
